# -*- coding: utf-8 -*-
"""firma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KV9yz79gxRIREkvwYs24R-MTIxAR-B_
"""

import streamlit as st
from streamlit_drawable_canvas import st_canvas

from PIL import Image
import numpy as np
import fitz
import os


#=================================================
# CONFIG
#=================================================

PDF_ORIGINAL = "Calificaciones.pdf"

PDF_FIRMADO = "Calificaciones_Coooon_firma.pdf"


st.set_page_config(

    page_title="Firma de conformidad",

    layout="wide"

)


st.title("🖊️ Firma de Conformidad")


if not os.path.exists("firmas"):

    os.mkdir("firmas")


#=================================================
# SI NO EXISTE EL PDF FIRMADO,
# SE CREA UNA COPIA DEL ORIGINAL
#=================================================

if not os.path.exists(PDF_FIRMADO):

    import shutil

    shutil.copy(

        PDF_ORIGINAL,

        PDF_FIRMADO

    )


#=================================================
# ALUMNOS
#=================================================

alumnos = {

"242013865":"JESSICA ALCÁNTARA ORTEGA",

"242013779":"ALISON VIRIDIANA ALONSO AVIÑA",

"242014048":"MARISOL BAUTISTA HERNÁNDEZ",

"242013886":"ANTHONY ARTURO CRUZ RAMIREZ",

"242014003":"ARTURO ESTEBAN FLORES MARTINEZ",

"242013791":"LAURA LIZETH GARCÍA CRUZ",

"242017782":"ÁNGEL JAHIR GÓMEZ ZEPEDA",

"242013836":"CRISTOFER IBAÑEZ CORTES",

"242013869":"DANIEL JACINTO AMEZCUA",

"242014038":"SEIDY EUNICE NIEVES ANAYA",

"242013523":"BELEN PACHECO ROMERO",

"242014028":"JOSÉ EDUARDO PÉREZ COLIN",

"242013858":"IRVING EDUARDO PÉREZ SÁNCHEZ",

"242014047":"JAVIER RIOS MARTÍNEZ",

"242013966":"NATALY MARIANA SANTIAGO ROJO",

"242013827":"MARÍA FERNANDA ZAMUDIO HERNÁNDEZ"

}


#=================================================
# LISTA DESPLEGABLE
#=================================================

opciones = {

f"{nombre} ({matricula})":matricula

for matricula,nombre in alumnos.items()

}


seleccion = st.selectbox(

    "Seleccione su nombre",

    [""] + list(opciones.keys())

)


if seleccion != "":

    matricula = opciones[seleccion]

    nombre = alumnos[matricula]

    st.success(nombre)

    st.info(f"Matrícula: {matricula}")


    st.subheader("Firme en el recuadro")


    canvas_result = st_canvas(

        stroke_width=3,

        stroke_color="#000000",

        background_color="#FFFFFF",

        width=500,

        height=150,

        drawing_mode="freedraw",

        key="firma"

    )


    if st.button("Guardar firma"):


        if canvas_result.image_data is not None:


            img = Image.fromarray(

                canvas_result.image_data[:,:,:3]

                .astype(np.uint8)

            )


            archivo_png = f"firmas/{matricula}.png"


            img.save(

                archivo_png

            )


            st.success(

                "Firma guardada"

            )


            #======================================
            # ABRIR PDF FIRMADO
            #======================================


            pdf = fitz.open(

                PDF_FIRMADO

            )


            encontrado = False


            for i in range(

                len(pdf)

            ):


                pagina = pdf[i]


                # Buscar matrícula

                resultados = pagina.search_for(

                    matricula

                )


                if len(resultados)>0:


                    r = resultados[0]


                    #--------------------------------

                    # A la derecha del nombre

                    #--------------------------------


                    x1 = r.x1 + 420

                    y1 = r.y0 - 5

                    x2 = x1 + 60

                    y2 = y1 + 20


                    rect = fitz.Rect(

                        x1,

                        y1,

                        x2,

                        y2

                    )


                    # DIBUJAR RECTÁNGULO ROJO

#                    pagina.draw_rect(

#                        rect,

#                        color=(1,0,0),

#                        width=1

#                    )


                    pagina.insert_image(

                        rect,

                        filename=archivo_png,

                        keep_proportion=True

                    )


                    encontrado = True


                    break



            if encontrado:


                pdf.save(

                    PDF_FIRMADO,

                    incremental=True,

                    encryption=0

                )


                pdf.close()


                st.success(

                    "✅ Firma agregada al PDF"

                )


                with open(

                    PDF_FIRMADO,

                    "rb"

                ) as f:


                    st.download_button(

                        "⬇️ Descargar PDF actualizado",

                        f,

                        file_name=PDF_FIRMADO,

                        mime="application/pdf"

                    )


            else:


                st.error(

                    "No se encontró la matrícula en el PDF"

                )                
