# -*- coding: utf-8 -*-
"""Firma_profesor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rp2jKECgRDYs1HpGeJ9uOWIKULssi0YW
"""

import streamlit as st
from streamlit_drawable_canvas import st_canvas
from PIL import Image
import numpy as np
import io

# ======================================================
# CONFIGURACIÓN
# ======================================================

st.set_page_config(
    page_title="Firma Digital",
    layout="centered"
)

st.title("✍️ Firma Digital")

st.write("Firme dentro del recuadro.")

# ======================================================
# CANVAS
# ======================================================

canvas_result = st_canvas(
    fill_color="rgba(255,255,255,0)",
    stroke_width=3,
    stroke_color="#0057FF",       # Azul
    background_color="#FFFFFF",   # Fondo blanco
    height=250,
    width=700,
    drawing_mode="freedraw",
    key="firma",
)

# ======================================================
# GUARDAR FIRMA
# ======================================================

if canvas_result.image_data is not None:

    img = canvas_result.image_data.astype(np.uint8)

    # Convertir a PIL
    firma = Image.fromarray(img)

    # Crear fondo blanco
    fondo = Image.new("RGB", firma.size, (255, 255, 255))

    # Pegar la firma sobre el fondo blanco
    fondo.paste(firma, mask=firma.split()[3])

    st.subheader("Vista previa")

    st.image(fondo)

    # Guardar en memoria
    buffer = io.BytesIO()
    fondo.save(buffer, format="PNG")
    buffer.seek(0)

    st.download_button(
        "💾 Descargar Firma PNG",
        data=buffer,
        file_name="firma.png",
        mime="image/png",
    )