# -*- coding: utf-8 -*-
"""firma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KV9yz79gxRIREkvwYs24R-MTIxAR-B_
"""

import streamlit as st
from streamlit_drawable_canvas import st_canvas

from PIL import Image
import numpy as np
import fitz
import os

#=================================================
# CONFIGURACIÓN
#=================================================
st.write(os.listdir("."))

PDF_ORIGINAL = "Calificaciones.pdf"

st.write("Existe?:", os.path.exists(PDF_ORIGINAL))


st.set_page_config(
    page_title="Firma de conformidad",
    layout="wide"
)

st.title("🖊️ Firma de Conformidad")

st.write(
    "Seleccione su nombre y firme en el recuadro."
)

if not os.path.exists("firmas"):
    os.mkdir("firmas")


#=================================================
# ALUMNOS
#=================================================

alumnos = {

"242013865":"JESSICA ALCÁNTARA ORTEGA",

"242013779":"ALISON VIRIDIANA ALONSO AVIÑA",

"242014048":"MARISOL BAUTISTA HERNÁNDEZ",

"242013886":"ANTHONY ARTURO CRUZ RAMIREZ",

"242014003":"ARTURO ESTEBAN FLORES MARTINEZ",

"242013791":"LAURA LIZETH GARCÍA CRUZ",

"242017782":"ÁNGEL JAHIR GÓMEZ ZEPEDA",

"242013836":"CRISTOFER IBAÑEZ CORTES",

"242013869":"DANIEL JACINTO AMEZCUA",

"242014038":"SEIDY EUNICE NIEVES ANAYA",

"242013523":"BELEN PACHECO ROMERO",

"242014028":"JOSÉ EDUARDO PÉREZ COLIN",

"242013858":"IRVING EDUARDO PÉREZ SÁNCHEZ",

"242014047":"JAVIER RIOS MARTÍNEZ",

"242013966":"NATALY MARIANA SANTIAGO ROJO",

"242013827":"MARÍA FERNANDA ZAMUDIO HERNÁNDEZ"

}


#=================================================
# COORDENADAS DE FIRMAS
#=================================================

# x1,y1,x2,y2

coordenadas = {

"242013865":[465,137,560,165],

"242013779":[465,154,560,182],

"242014048":[465,171,560,199],

"242013886":[465,188,560,216],

"242014003":[465,205,560,233],

"242013791":[465,222,560,250],

"242017782":[465,239,560,267],

"242013836":[465,256,560,284],

"242013869":[465,273,560,301],

"242014038":[465,290,560,318],

"242013523":[465,307,560,335],

"242014028":[465,324,560,352],

"242013858":[465,341,560,369],

"242014047":[465,358,560,386],

# Página 2

"242013966":[465,75,560,105],

"242013827":[465,92,560,122]

}


#=================================================
# LISTA DESPLEGABLE
#=================================================

opciones = {

f"{nombre} ({matricula})":matricula

for matricula,nombre in alumnos.items()

}


seleccion = st.selectbox(

    "Seleccione su nombre",

    [""] + list(opciones.keys())

)


#=================================================
# SI ELIGE UN ALUMNO
#=================================================

if seleccion != "":

    matricula = opciones[seleccion]

    nombre = alumnos[matricula]

    st.success(nombre)

    st.info(f"Matrícula: {matricula}")

    st.subheader("Firme en el recuadro")


    canvas_result = st_canvas(

        stroke_width=3,

        stroke_color="#000000",

        background_color="#FFFFFF",

        width=500,

        height=150,

        drawing_mode="freedraw",

        key="firma"

    )


    if st.button("Guardar firma"):


        if canvas_result.image_data is not None:


            img = Image.fromarray(

                canvas_result.image_data[:,:,:3]

                .astype(np.uint8)

            )


            archivo_png = f"firmas/{matricula}.png"


            img.save(archivo_png)


            st.success("Firma guardada.")


            #=====================================
            # ABRIR PDF
            #=====================================

            pdf = fitz.open(PDF_ORIGINAL)


            # Página

            pagina_pdf = 0


            if matricula in [

                "242013966",

                "242013827"

            ]:

                pagina_pdf = 1


            pagina = pdf[pagina_pdf]


            x1,y1,x2,y2 = coordenadas[matricula]


            rect = fitz.Rect(

                x1,

                y1,

                x2,

                y2

            )


            pagina.insert_image(

                rect,

                filename=archivo_png,

                keep_proportion=True

            )


            salida = f"Firmado_{matricula}.pdf"


            pdf.save(

                salida,

                incremental=False,

                encryption=0

            )


            pdf.close()


            st.success(

                "✅ PDF firmado correctamente"

            )


            with open(

                salida,

                "rb"

            ) as f:


                st.download_button(

                    "⬇️ Descargar PDF firmado",

                    f,

                    file_name=salida,

                    mime="application/pdf"

                )
